### ISSUE TITLE
Cannot get menu to work

### ISSUE THREAD

**Issue by du8die** [getgrav/grav-theme-woo#5]
Need assistance getting menu to work. 

I've set up a new site exactly like the demo - and cannot get the top nav to populate with the menu items.

Please advise.

**Comment by rhukster** [comment]
Did you create a new folder/page and ensure it's visible? https://learn.getgrav.org/basics/basic-tutorial#adding-a-new-page

The `02.` part in the folder name makes it visible.  Otherwise you would have to just set `visible: true` in the page frontmatter.

**Comment by du8die** [comment]
Hi. Thanks for the quick reply.

Here's my folder structure:

`01.Home`
`├─ _banner`
`├─ _features`
`├─ _pricing`
`02.Blog`

01 and 02 show up.
The modular pages don't. 

Any other places I should be looking?

Thanks

**Comment by rhukster** [comment]
Modular pages don't show up in the menu by default.  They are just building blocks to build a single page.  If you want to provide an on-page menu it's going to take some custom code.  Antimatter has an example of this:

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/modular.html.twig#L29-L48

**Comment by rhukster** [comment]
Actually depending on your needs and based on the existing woo navigation code: https://github.com/getgrav/grav-theme-woo/blob/develop/templates/partials/navigation.html.twig

you can simply add some menu items to your site.yaml if you want some hardcoded ones.
